-- Trivia Rush manifest-derived category and question verification
-- Generated by scripts/build-question-seed.mjs. Do not edit this SQL by hand.
-- Every query is read-only.

with expected(category_id, label, sort_order, icon_key, color, easy, medium, hard, total) as (
  values
    ('science', 'Science', 10, 'flask', '#41E28C', 40, 40, 20, 100),
    ('history', 'History', 20, 'landmark', '#FFD54A', 40, 40, 20, 100),
    ('geography', 'Geography', 30, 'globe', '#3EE7DB', 40, 40, 20, 100),
    ('entertainment', 'Entertainment', 40, 'film', '#FF4F9B', 40, 40, 20, 100),
    ('sport', 'Sport', 50, 'trophy', '#FF8A4C', 40, 40, 20, 100),
    ('technology', 'Technology', 60, 'cpu', '#7C83FF', 40, 40, 20, 100),
    ('gaming', 'Gaming', 70, 'gamepad', '#B66CFF', 40, 40, 20, 100),
    ('food_drink', 'Food & Drink', 80, 'utensils', '#FFB347', 40, 40, 20, 100),
    ('nature_animals', 'Nature & Animals', 90, 'paw', '#62D26F', 40, 40, 20, 100),
    ('art_literature', 'Art & Literature', 100, 'palette_book', '#F47CD4', 40, 40, 20, 100),
    ('game_of_thrones', 'Game of Thrones', 110, 'dragon', '#9B1C1C', 35, 45, 20, 100),
    ('mythology', 'Mythology', 120, 'thunderbolt', '#C9A227', 35, 45, 20, 100),
    ('harry_potter', 'Harry Potter', 130, 'wand', '#4B2E83', 35, 45, 20, 100),
    ('marvel_cinematic_universe', 'Marvel Cinematic Universe', 140, 'shield', '#ED1D24', 35, 45, 20, 100)
), actual as (
  select
    qc.id as category_id,
    qc.label,
    qc.sort_order,
    qc.icon_key,
    qc.color,
    count(q.id) filter (where q.is_active and q.difficulty = 'easy')::integer as easy,
    count(q.id) filter (where q.is_active and q.difficulty = 'medium')::integer as medium,
    count(q.id) filter (where q.is_active and q.difficulty = 'hard')::integer as hard,
    count(q.id) filter (where q.is_active)::integer as total
  from public.question_categories qc
  left join public.trivia_questions q on q.category_id = qc.id
  where qc.is_active
  group by qc.id, qc.label, qc.sort_order, qc.icon_key, qc.color
)
select
  expected.* ,
  actual.easy as actual_easy,
  actual.medium as actual_medium,
  actual.hard as actual_hard,
  actual.total as actual_total,
  actual.category_id is not null
    and actual.label = expected.label
    and actual.sort_order = expected.sort_order
    and actual.icon_key = expected.icon_key
    and actual.color = expected.color
    and actual.easy = expected.easy
    and actual.medium = expected.medium
    and actual.hard = expected.hard
    and actual.total = expected.total as matches_manifest
from expected
left join actual using (category_id)
order by expected.sort_order;

select
  count(*) filter (where is_active) = 14 as active_category_count_matches,
  (select count(*) from public.trivia_questions where is_active) = 1400 as active_question_count_matches
from public.question_categories;

select correct_index, count(*) as questions
from public.trivia_questions
where is_active
group by correct_index
order by correct_index;

select
  count(*) filter (where char_length(btrim(question_text)) not between 10 and 240) as invalid_question_text,
  count(*) filter (where not trivia_private.question_answers_are_valid(answers)) as invalid_answers,
  count(*) filter (where correct_index not between 0 and 2) as invalid_indexes,
  count(*) filter (where source_url !~ '^https://') as invalid_source_urls,
  count(*) filter (where verified_at is null) as missing_verified_at
from public.trivia_questions
where is_active;

select count(*) as duplicate_normalised_questions
from (
  select lower(regexp_replace(btrim(question_text), '\s+', ' ', 'g'))
  from public.trivia_questions
  where is_active
  group by lower(regexp_replace(btrim(question_text), '\s+', ' ', 'g'))
  having count(*) > 1
) duplicates;

select count(*) = 400 as frozen_legacy_key_count_matches
from public.trivia_questions
where question_key ~ '^(got|myth|hp|mcu)_[0-9]{3}$';

select * from public.get_question_categories();

select grantee, table_name, privilege_type
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name in ('question_categories', 'trivia_questions')
  and grantee in ('anon', 'authenticated')
order by table_name, grantee, privilege_type;
